name: Playwright E-commerce Tests
on:
  push:
    branches: [main, master, newWorkflowsStrategy]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  checks: write
  id-token: write

env:
  BASE_URL: ${{ vars.BASE_URL }}
  API_URL: ${{ vars.API_URL }}
  DEFAULT_USER_EMAIL: ${{ vars.DEFAULT_USER_EMAIL }}
  DEFAULT_USER_PASSWORD: ${{ vars.DEFAULT_USER_PASSWORD }}

jobs:
  prepare-env:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: test-env-ecommerce
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e \"console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)\")" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-cache
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

  run-setup-tests:
    needs: [prepare-env]
    timeout-minutes: 2
    runs-on: ubuntu-latest
    environment: test-env-ecommerce
    steps:
      - name: Run setup tests
        run: npm run test:setup:workflow
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: setup-tests-report
          path: ./playwright-report/**/*.*
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: './playwright-report/results.xml'

  run-tests:
    needs: [prepare-env, run-setup-tests]
    runs-on: ubuntu-latest
    environment: test-env-ecommerce
    steps:
      - name: Run all tests
        run: npm run test:all
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-tests-report
          path: ./playwright-report/**/*.*
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: './playwright-report/results.xml'
